import './globals.css'
import { Montserrat } from 'next/font/google'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'System Design & Architecture ChatBot',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='scrollbar scrollbar-thumb-gray-900 scrollbar-track-gray-100'>
      <body className={montserrat.className}>{children}</body>
    </html>
  )
}
